STRUCTURE_PROMPT = """
You are an AI model tasked with designing a detailed outline for a 5-paragraph book report.
Do NOT write the full essay. Instead, produce a structured plan that includes:

The documents you will be analyzing are {FILENAMES}

USE ONLY THOSE DOCUMENTS

1. A clear thesis statement focusing on how each of the texts given explore the central user prompt: {USER_PROMPT}
2. Three body paragraphs (each referencing key points and specific citations from the texts).
3. A concluding paragraph summarizing the argument.

Here is the relevant background from the official instructions (summarized from the 'Take Home Assignment Instructions' document):
----------------------------------------------------------------
- The report should compare how each book handles the theme specified by the user in their prompt.
- Provide a clear thesis, coherent arguments, and cite relevant sections from each novel.
- No human reading or manual summarizing – everything is generated by AI tools.
- The final deliverable (when fully written later) should be 5 paragraphs: introduction (thesis), 3 body paragraphs (analysis & citations), and a conclusion.
- Cite relevant sections from each novel as accurately as possible.
----------------------------------------------------------------

Additionally, here is the user’s own specific request or focus. FOCUS ON THIS. THIS is the essay topic:
----------------------------------------------------------------
{USER_PROMPT}
----------------------------------------------------------------

And also, here is some context from the books associated directly with the user's prompt. Each chunk will have its associated book file and even the chunk number associated with it. 
You will have the ability to retrieve your own context later, based on the structure you create here.

----------------------------------------------------------------
{USER_CONTEXT}
----------------------------------------------------------------

Based on the above:
- Return ONLY a structured outline for the essay (not the full prose).
- Make sure each paragraph has a topic sentence and bullet points indicating which novel passages you plan to cite.
- Conclude with a brief summary line that restates the thesis.

Please respond with your outline in a clearly organized format (e.g., bullet points or headings).
"""



CONTEXT_PROMPT = """
You have the following outline for a 5-paragraph essay comparing how each of the texts provided address the user question of {USER_PROMPT}:

----------------------------------------------------------------
{OUTLINE_TEXT}
----------------------------------------------------------------


The documents you will be analyzing are {FILENAMES}

USE ONLY THOSE DOCUMENTS

Your task now is to propose up to four search queries that could help retrieve additional passages from these novels. 
Each query should:
- Aim to enrich the discussion on the prompt in the outline
- Target relevant scenes, quotes, or details that connect directly to the outline’s key points
- Focus on obtaining deeper textual evidence to support each paragraph in the outline.

Output only the queries, strictly in the following format, one per line, and no extra commentary:

Query1
Query2
Query3
Query4

Remember:
- A maximum of 4 queries
- No additional explanation or formatting
"""


GENERATE_PROMPT = """
You are an AI assistant tasked with composing a final 5-paragraph book report based on the following:


The documents you will be analyzing are {FILENAMES}

USE ONLY THOSE DOCUMENTS

1. The user prompt:
----------------------------------------------------------------
{USER_PROMPT}
----------------------------------------------------------------

2. The outline structure already established:
----------------------------------------------------------------
{STRUCTURE}
----------------------------------------------------------------

3. The user’s additional context or focus:
----------------------------------------------------------------
{USER_CONTEXT}
----------------------------------------------------------------

4. Supplementary text or novel excerpts:
----------------------------------------------------------------
{MORE_CONTEXT}
----------------------------------------------------------------

5. Some other analysis/brainstorming you have done:
----------------------------------------------------------------
{CONTEXT_RESPONSE}
----------------------------------------------------------------

INSTRUCTIONS:
- Write a cohesive, well-structured 5-paragraph essay that adheres to the structure.
- The essay should be AT LEAST 600 words
- Accurately reference or cite sections from the texts where appropriate. For each citation, put a number ex. [1] and, at the end of the essay, maintain a citation list for each chunk
- AGAIN, remember to CITE your chunks. The chunks are very important. DO NOT quote passages/context that is untrue or did not appear.
- MAKE SURE you synthesize ideas FROM ALL the texts/documents, none should be left out
- Maintain clarity, coherence, and strong transitions between paragraphs. Be emotive, emotional, and insightful. Create a genuine, convincing analysis.


MAKE SURE TO CITE SOURCES (ex. [1] --> XYZ book chunk A)

Deliver a single, continuous text output of exactly five paragraphs. No additional formatting or commentary should be included outside of these paragraphs. MAKE SURE YOU INCLUDE CITATIONS of WORKS AND CHUNKS
"""